main:
    name: ${now:%Y%m%d-%H%M%S}_${env.id}_${main.suffix}
    suffix:
    logs_dir: /checkpoint/${env:USER}/offline-gcrl/logs/${main.name}
    save_interval: 100

env:
    id: maze_U4rooms
    success_thresh: 0.5
    max_episode_steps: 100
    action_repeat: 1
    random_start_pos: false
    obs:
        type: vec
        state_size:
        obs_size:
    action_dim: 2

exploration_buffer:
    data_dir: /checkpoint/${env:USER}/offline-gcrl/data/maze_U4rooms-rsp/random
    num_procs: 10

replay_buffer:
    capacity: 100000
    reward_scaling: 0.01

optim:
    num_epochs: 1001

eval:
    num_episodes: 500
    num_procs: 10

sac:
    policy:
        type: Gaussian
        hidden_size: 256
        head:
            type: fc
            out_size: 16
            hidden_size: 64
            n_layers: 3
            normalize: true
    
    optim:
        lr: 0.001 
        batch_size: 1024
        num_updates_per_epoch: 1000
        tau: 0.005
        gamma: 0.99
        target_update_interval: 1
        entropy:
            alpha: 0.01
            auto_tuning: false
            lr: 0.0003
        policy:
            lr: ${sac.optim.lr}  #use different LR for the policy

rnet:
    load_from: /checkpoint/${env:USER}/offline-gcrl/rnet/maze_U4rooms-rsp/
    model:
        feat_size: 16
        hidden_size: 64
        comparator: net
        n_layers: 3
        remove_velocity: true #remove velocity for maze
        dims_to_keep:
    dataset:
        thresh: 10
        in_traj_ratio: 0.5
        num_pairs:
            train: 500000
            val: 100000
    train:
        lr: 0.001
        num_epochs: 10
        batch_size: 512
        num_workers: 32
        weight_decay: 0.00001
    memory:
        thresh: 0
        capacity: 500
        skip: 1
        skip_traj: 0.05 #percentage of trajectories to skip

hydra:
    launcher:
        nodes: 1
        cpus_per_task: 10
        signal_delay_s: 30
        timeout_min: 4230
        gpus_per_node: 1
        tasks_per_node: 1
        partition: learnlab
        name: ${main.name}

    job_logging:
        formatters:
            simple:
                format: '[%(levelname)s] - %(message)s'

    sweep:
        dir: /checkpoint/${env:USER}/offline-gcrl/logs/multirun/${main.name}

defaults:
    - override hydra/launcher: submitit_slurm
