main:
    name: ${now:%Y%m%d-%H%M%S}_${env.id}_${main.suffix}
    suffix:

env:
    id: maze_U4rooms
    success_thresh: 0.5
    max_episode_steps: 100
    action_repeat: 1
    random_start_pos: false
    obs:
        type:
        vec_size:
        rgb_size:
    action_dim:

exploration_buffer:
    data_dir: data/maze_U4rooms-rsp/random
    num_procs: 20

replay_buffer:
    capacity: 100000
    reward_scaling: 0.01

optim:
    num_epochs: 10

eval:
    num_episodes: 500
    num_procs: 10

sac:
    policy:
        type: Gaussian
        hidden_size: 256
        head:
            type: fc
            out_size: 16
            hidden_size: 64
            n_layers: 3
            normalize: true
    
    optim:
        lr: 0.001 
        batch_size: 1024
        num_updates_per_epoch: 1000
        tau: 0.005
        gamma: 0.99
        target_update_interval: 1
        entropy:
            alpha: 0.01
            auto_tuning: false
            lr: 0.0003
        policy:
            lr: ${sac.optim.lr}  #use different LR for the policy

hydra:
    run:
        dir: .
