# @package _global_
defaults:
    - /env/pusher

main:
    suffix: baseline-${replay_buffer.algo}
    reward: act_model

sac:
    optim:
        gamma: 0.99
        entropy:
            alpha: 0.005
        lr: 0.0001

replay_buffer:
    reward_scaling: 1
    num_procs: 20
