# @package _global_
defaults:
    - /env/pusher

main:
    suffix: ours
    subgoal_transitions: True
    edge_transitions: False
    reward_sigm_weight: 100

rnet:
    dataset:
        thresh: 5
    train:
        lr: 0.001
        num_epochs: 100
    memory:
        capacity: 1000
        node_skip: 0.01
        edge_skip: 0.01

sac:
    optim:
        gamma: 0.95
        entropy:
            alpha: 0.0001
        lr: 0.0005

replay_buffer:
    reward_scaling: 0.01
    num_procs: 20
